/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects and is committed here
// so TypeScript can resolve Next.js types before the first local build.
